### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by failoften** [shiffman/Rekognition-for-Processing#15]
This may be due to Rekognition's new policies, but this version is now throwing a null pointer exception. 

Line 36
faces = rekog.recognize(filename);

**Comment by failoften** [comment]
```
java.lang.NullPointerException
at http.requests.PostRequest.send(Unknown Source)
at rekognition.faces.Rekognition.recognizeFacesPath(Unknown Source)
at rekognition.faces.Rekognition.recognize(Unknown Source)
at FaceRecognizeExample.setup(FaceRecognizeExample.java:55)
at processing.core.PApplet.handleDraw(PApplet.java:2361)
at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:240)
at processing.core.PApplet.run(PApplet.java:2256)
at java.lang.Thread.run(Thread.java:745)
```
